import { Header } from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto_Flex as Roboto, Lobster } from "next/font/google";

const roboto = Roboto({ subsets: ["latin"], variable: "--font-roboto" });
const lobster = Lobster({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lobster",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${lobster.variable} font-sans text-slate-900`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
